language: node_js
node_js: node
notifications:
  slack:
    secure: t4Fc5Qkwj/2wUeN5kURqvQGsw0XUgCzxQxmUkQkQEQHpBuZUxHutWfE9KjrCTX6wRv9mCUcRgnwfTZe/ZcZjvGO1ZksNXHwS4TIMpceS4I78Mw4IHe+vqX1fCBkkGVhNYQC5hloY0cHBMF7yMKDq7Axmp7zWhQIOjdEfYX3BM7+taxAR6nanNjsI3oQhML04lUEyq8/CDnH8YoQ53our/6l30XYUxxGRTQ+ZNma73Vf/HUo+HNxLG7VABF59auJkLSqKBK3tiWvx5s3Jf6FShwv3cFjqgLSlorEg7NhI4KKrQeBy7AaPGZ/vVuDWyCA2fRbznki4rbf+RA3SB+JUn3e9PvjoXICPfcvhFhcPtmAS+oZ99A3VqZ8kvbUyAwDbMN3//g62mo7+ylOS3O2D89/q+NimfYU4KIQqnj+pw/2sWAHQb6dsukFJdYloDGWnXpfUn/h/fZiBZQQMCV25ov2vYNFiwrRxLFVKNQ2WGurfN56c7SDpFMwKe9PeE7ybFH+XcGjIvbdHZZEVVhS8t5i3y9ti4bZlHXqQWFSE5KL7/+vJz6aT2cj5zU4rXD9Q2Bv2RCk2cBV8Hfx7kcQoueVeWtbOFX1WWfEOxHyNvBaJ1sAdnYrtVBYlhPWJ0PT70N9UfGaXfm6kdvt/O3OXcpZiuYRS98vOjDpT53QjSJo=
deploy:
  provider: heroku
  api_key:
    secure: DlmP7JFZLZz65/JN9gi39DowJ4x9102JXWnacixJtfNTSWSJE2EibhbefIUFW1lh83yHRnRSE+lxtiu5Em/MunPf+RsBnfF75UWtvu12UftEjHrOIwSUTDyzvhpcJtHLAW+ngdNRx3jU5c+GZS+BDhqgV3YG4O9icMV+q/nAV7WUY68w7uu7kv5fu1tKTtQNN0o1e0B/BCQVuCPlh0bh4hmBpRH+k0B7o0ymQiR9MViN8XT1fLeHAvgFg8HUAN0+H3yOishcxXqh12POUChXGhImbgPfRJ5NijMsR6zmcN6qDIwcPTLggYvrIsrjOGtYwwKbzBnpNroyITy1nY8lPUBCnJyMkVD4nO96RjCt//OQWzn9HCvRbVvz2/CMjiAyTcgv5jgzSFm16/pZnYvPtug1w0i4rw56J6yzsNFEtYqmbHv6riDO6qBGpEPeHUsIRG7YvtV4TdC5ITPYts9wenBe5VMoYa3sVkCS07US4ygleutSb6rtxnExMp4onGEk7l67ru3ecMKcPdjl1+i+3WzGNRJXV9UAroA4mmjNC9iLoufLB91fZDoAT95WrX2n+OtdxK7yzcCraKHAFi9BFctj4dYJZO0/eaJCC21PH4m/pY047YnXHggnxXyJPXxi13aOJup/PmDdXwkfVBWfUOj/5Lxng9cNGxoQTWRyvRY=
  app: boiling-river-85178
  on:
    repo: motku/crud-api
